name : push events workflow

on : push 

jobs :
  unit-testing :
    runs-on: ubuntu-latest
    
    steps :
      - name : Checkout Code
        uses : actions/checkout@v2
        
      - name : Install Package
        run  : pip install pytest numpy pandas
        
      - name : Run Test
        run  : pytest test_preprocessig.py 
